services:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123123@Admin
      MYSQL_DATABASE: example_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"


  redis:
    image: redis:latest
    ports:
      - "6379:6379"